name: Publish TechDocs Site

on:
  push:
    branches: [main, master]
    paths:
      - "**/docs/**"
      - "mkdocs.yml"

jobs:
  publish-techdocs-site:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/heroku-backstage-techdocs-action@stable
        with:
          component-name: backstage-test
